workflows:
  test_1:
    name: FirstWorkFlow
    scripts:
      - flutter pub get
      - name : Build Apk
        script: flutter build apk -- release
    artifacts:
      -   build/**/output/**/*.apk